### ISSUE TITLE
吸附后的View如何设置点击事件

### ISSUE THREAD

**Issue by go-2021** [chenpengfei88/StickyItemDecoration#10]
有个需求就是点击可以隐藏或打开列表，如何给吸附后的View设置点击事件，尝试了下没有解决，不知作者是否有好的方案，谢谢！

**Comment by chenpengfei88** [comment]
mStickyItemView添加事件不可以？

**Comment by go-2021** [comment]
不行呀，设置setOnClickListener不起作用，点击没有回调

**Comment by chenpengfei88** [comment]
不行的话只能重写RecyclerView的onTouchEvent方法了

**Comment by go-2021** [comment]
谢谢您的回答
我发现用canvas直接画出的View是无法设置点击事件的
我的解决办法是给StickyItemDecoration传递一个ViewGroup，然后把mStickyItemView放入ViewGroup中，在滑动时通过mStickyItemView.setTranslationY来实现粘性View的滚动效果，这样就可以响应点击事件了
