### ISSUE TITLE
可以添加头吗？

### ISSUE THREAD

**Issue by fengfengfeng1234** [chenpengfei88/StickyItemDecoration#11]
比如demo中：
注释掉：
`//        Performer performer = new Performer("香港明星");
//        performers.add(performer);`

可以不显示下面的一个title？

**Comment by chenpengfei88** [comment]
没理解

**Comment by fengfengfeng1234** [comment]
开始几个数据 不需要吸顶效果，到达了中途部分在开始。

**Comment by chenpengfei88** [comment]
暂时不支持
