### ISSUE TITLE
涉及到了正序倒叙切换

### ISSUE THREAD

**Issue by liguangze** [chenpengfei88/StickyItemDecoration#14]
正序倒叙切换的时候，清空数据从新请求后，title的第一条数据不会刷新，content的全部都能刷新

**Comment by liguangze** [comment]
请问源码中刷新数据的地方在哪里呢

**Comment by chenpengfei88** [comment]
数据刷新就是通过适配器的通知方法

**Comment by liguangze** [comment]
现在的问题就是title的第一条数据不会刷新，第二条就会，content的全部都能刷新呢，

**Comment by chenpengfei88** [comment]
你可以把StickyItemDecoration类里bindDataForStickyView方法的mBindDataPosition == position判断去掉；当时加这个判断是为了防止重复绑定数据

**Comment by liguangze** [comment]
涉及到上拉 下拉，还是有点小问题，我看自己能改吗，
感谢开源

**Comment by chenpengfei88** [comment]
嗯，客气，有问题可以提出来一起完善
