### ISSUE TITLE
完善部分需求

### ISSUE THREAD

**Issue by ytsxg123** [chenpengfei88/StickyItemDecoration#3]
实际运行中，这种粘连是随着数据排序跟着某一条数据出来的。
比如 手机通讯录用这种方式实现。那么数据肯定是不会像这样的，那么就需要处理展示数据的item了
以下是我的修改结果
1、StickyView 加入一个方法
/**
     * 获取吸附View
     */
    View getStickView(RecyclerView.ViewHolder vh);
在adapter中实现这个接口
 @Override
    public View getStickView(RecyclerView.ViewHolder vh) {
        if (vh instanceof TitleVH) {
            return ((TitleVH) vh).mTitle;
        }
        return null;
在顶部布局中，有两个控件，一个标题一个内容，此刻只获取标题的View
2、mStickyItemView的获取方式由原来的改为mStickyItemView = mStickyView.getStickView(mViewHolder);
3、bindDataForStickyView方法中原代码：//        mStickyItemViewHeight = mViewHolder.itemView.getBottom() - mViewHolder.itemView.getTop();替换为mStickyItemViewHeight = mStickyItemView.getBottom() - mStickyItemView.getTop();
测试结果通过，可以，支持原效果能支持的需求

另建议：在具体适配器中实现StickyView接口 在构造中传入此接口。
如不介意：我会在我的github上传上我修改过后的代码，当然会加入你的链接
如有问题，请联系我，本人邮箱：sunxiaogang0214@163.com

**Comment by chenpengfei88** [comment]
没懂，通讯录的数据和我项目中测试的数据有区别吗
