### ISSUE TITLE
动画效果

### ISSUE THREAD

**Issue by mallxiaodoudou** [chenpengfei88/StickyItemDecoration#5]
东西是好东西，好用，简单，使用多布局的方式完全解耦了，但是有一点，你的Decoration动画总感觉不是很顺滑，上滑动的时候上一个Decoration消失在屏幕上，这个Decoration还跟着上一个走了一段路才突然显示出来，没有那种连贯置顶的感觉，看了源码找不出原因

**Comment by mallxiaodoudou** [comment]
又遇到一个问题，如果我添加了 头布局，那么overlay展示在头布局上，这个有办法解决吗？

**Comment by chenpengfei88** [comment]
第一个问题我到是没遇到过；第二个问题不是很懂
