### ISSUE TITLE
数据格式是两个层级的你这个怎么实现

### ISSUE THREAD

**Issue by open9527** [chenpengfei88/StickyItemDecoration#6]
[
            {
                "type_id": 1,
                "type_name": "类型1",
                "type_templet": [
                    {
                        "type_id": 1,
                        "templet_id": 2,
                        "templet_name": "时尚"
                    },
                    {
                        "type_id": 1,
                        "templet_id": 57,
                        "templet_name": "模板2"
                    },
                    {
                        "type_id": 1,
                        "templet_id": 59,
                        "templet_name": "rgte"
                    },
                    {
                        "type_id": 1,
                        "templet_id": 62,
                        "templet_name": "muban"
                    },
                    {
                        "type_id": 1,
                        "templet_id": 63,
                        "templet_name": "全球性"
                    },
                    {
                        "type_id": 1,
                        "templet_id": 65,
                        "templet_name": "rgter"
                    },
                    {
                        "type_id": 1,
                        "templet_id": 66,
                        "templet_name": "反而个人"
                    },
                    {
                        "type_id": 1,
                        "templet_id": 67,
                        "templet_name": "反而个人"
                    },
                    {
                        "type_id": 1,
                        "templet_id": 68,
                        "templet_name": "反而"
                    },
                    {
                        "type_id": 1,
                        "templet_id": 73,
                        "templet_name": "啦啦啦"
                    }
                ]
            },
            {
                "type_id": 7,
                "type_name": "类型7",
                "type_templet": [
                    {
                        "type_id": 7,
                        "templet_id": 60,
                        "templet_name": "33"
                    },
                    {
                        "type_id": 7,
                        "templet_id": 64,
                        "templet_name": "模板1"
                    }
                ]
            }
        ]

**Comment by chenpengfei88** [comment]
这个实现要自己在适配器里做处理了，和这个项目就没什么关系了
