### ISSUE TITLE
最后一个吸附Title问题

### ISSUE THREAD

**Issue by Xuzqing** [chenpengfei88/StickyItemDecoration#7]
当最后一个吸附Title的Content高度大于屏幕高度时，滑动到最后一个吸附Title时，此Title会闪动。
例如：将源码的getData()方法中 “导演” 及其子Content注释掉：
//        Performer performerDy = new Performer("导演");
//        performers.add(performerDy);
//        Performer jzk = new Performer("贾樟柯", 10);
//        performers.add(jzk);
//        Performer ly = new Performer("李杨", 10);
//        performers.add(ly);
//        Performer fxg = new Performer("冯小刚", 10);
//        performers.add(fxg);
//        Performer lyy = new Performer("娄烨", 10);
//        performers.add(lyy);
//        Performer zym = new Performer("张艺谋", 10);
//        performers.add(zym);

此时滑动到“NBA明星”的吸附Title时，此吸附Title闪动（与其他吸附Title过度效果不一致）。

**Comment by chenpengfei88** [comment]
已修复
